name: Build & Release
on:
  push:
    branches:
      - master
jobs:
  github-release-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm install
      - run: npm run build
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./release.zip ./vuetorrent
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Stable Build"
          files: release.zip
